In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [3]:
# Tambahkan huruf r sebelum tanda kutip pembuka
data = pd.read_csv(r'C:\Users\asus\OneDrive\Documents\statistika\Estimasi\MovieData-2018-2020.csv')

data.head(30)

,name,rating,genre,year,released,score,votes,director,writer,star,country,budget,gross,company,runtime
0,A Quiet Place,PG-13,Drama,2018,"April 6, 2018 (United States)",7.5,456000.0,John Krasinski,Bryan Woods,Emily Blunt,United States,17000000.0,3.503204e+08,Paramount Pictures,90.0
1,Avengers: Infinity War,PG-13,Action,2018,"April 27, 2018 (United States)",8.4,897000.0,Anthony Russo,Christopher Markus,Robert Downey Jr.,United States,321000000.0,2.048360e+09,Marvel Studios,149.0
2,Deadpool 2,R,Action,2018,"May 18, 2018 (United States)",7.7,505000.0,David Leitch,Rhett Reese,Ryan Reynolds,Canada,110000000.0,7.864705e+08,Twentieth Century Fox,119.0
3,Bohemian Rhapsody,PG-13,Biography,2018,"November 2, 2018 (United States)",7.9,476000.0,Bryan Singer,Anthony McCarten,Rami Malek,United Kingdom,52000000.0,9.119026e+08,Twentieth Century Fox,134.0
4,Black Panther,PG-13,Action,2018,"February 16, 2018 (United States)",7.3,661000.0,Ryan Coogler,Ryan Coogler,Chadwick Boseman,United States,200000000.0,1.347598e+09,Marvel Studios,134.0
5,Hereditary,R,Drama,2018,"June 8, 2018 (United States)",7.3,259000.0,Ari Aster,Ari Aster,Toni Collette,United States,10000000.0,8.023966e+07,PalmStar Media,127.0
6,A Simple Favor,R,Comedy,2018,"September 14, 2018 (United States)",6.8,136000.0,Paul Feig,Darcey Bell,Anna Kendrick,Canada,20000000.0,9.764462e+07,BRON Studios,117.0
7,Aquaman,PG-13,Action,2018,"December 21, 2018 (United States)",6.9,404000.0,James Wan,David Leslie Johnson-McGoldrick,Jason Momoa,United States,160000000.0,1.148486e+09,Warner Bros.,143.0
8,Ready Player One,PG-13,Action,2018,"March 29, 2018 (United States)",7.4,388000.0,Steven Spielberg,Zak Penn,Tye Sheridan,United States,175000000.0,5.828937e+08,Warner Bros.,140.0
9,Spider-Man: Into the Spider-Verse,PG,Animation,2018,"December 14, 2018 (United States)",8.4,411000.0,Bob Persichetti,Phil Lord,Shameik Moore,United States,90000000.0,3.755408e+08,Sony Pictures Entertainment (SPE),117.0
10,Mission: Impossible - Fallout,PG-13,Action,2018,"July 27, 2018 (United States)",7.7,303000.0,Christopher McQuarrie,Bruce Geller,Tom Cruise,United States,178000000.0,7.916574e+08,Paramount Pictures,147.0
11,Venom,PG-13,Action,2018,"October 5, 2018 (United States)",6.7,387000.0,Ruben Fleischer,Jeff Pinkner,Tom Hardy,China,100000000.0,8.560852e+08,Avi Arad Productions,112.0
12,Green Book,PG-13,Biography,2018,"November 16, 2018 (United States)",8.2,414000.0,Peter Farrelly,Nick Vallelonga,Viggo Mortensen,United States,23000000.0,3.217527e+08,Participant,130.0
13,Crazy Rich Asians,PG-13,Comedy,2018,"August 15, 2018 (United States)",6.9,152000.0,Jon M. Chu,Peter Chiarelli,Constance Wu,United States,30000000.0,2.385392e+08,Warner Bros.,120.0
14,Ant-Man and the Wasp,PG-13,Action,2018,"July 6, 2018 (United States)",7.0,333000.0,Peyton Reed,Chris McKenna,Paul Rudd,United States,162000000.0,6.226741e+08,Marvel Studios,118.0
15,BlacKkKlansman,R,Biography,2018,"August 10, 2018 (United States)",7.5,236000.0,Spike Lee,Charlie Wachtel,John David Washington,United States,15000000.0,9.341371e+07,Focus Features,135.0
16,The Predator,R,Action,2018,"September 14, 2018 (United States)",5.3,120000.0,Shane Black,Fred Dekker,Boyd Holbrook,United States,88000000.0,1.605421e+08,Twentieth Century Fox,107.0
17,White Boy Rick,R,Crime,2018,"September 14, 2018 (United States)",6.5,33000.0,Yann Demange,Andy Weiss,Matthew McConaughey,United States,29000000.0,2.595748e+07,LBI Productions,111.0
18,Solo: A Star Wars Story,PG-13,Action,2018,"May 25, 2018 (United States)",6.9,306000.0,Ron Howard,Jonathan Kasdan,Alden Ehrenreich,United States,275000000.0,3.929248e+08,Lucasfilm,135.0
19,Midnight Sun,PG-13,Drama,2018,"March 23, 2018 (United States)",6.6,26000.0,Scott Speer,Kenji Bando,Bella Thorne,United States,2800000.0,2.736547e+07,Boies / Schiller Film Group,91.0
20,Under the Silver Lake,R,Crime,2018,"April 19, 2019 (United States)",6.5,36000.0,David Robert Mitchell,David Robert Mitchell,Andrew Garfield,United States,8500000.0,2.053469e+06,Vendian Entertainment,139.0
21,Den of Thieves,R,Action,2018,"January 19, 2018 (United States)",7.0,99000.0,Christian Gudegast,Christian Gudegast,Gerard Butler,United States,30000000.0,8.050962e+07,STX Films,140.0
22,Annihilation,R,Adventure,2018,"February 23, 2018 (United States)",6.8,292000.0,Alex Garland,Alex Garland,Natalie Portman,United Kingdom,40000000.0,4.307092e+07,Paramount Pictures,115.0
23,Red Sparrow,R,Action,2018,"March 2, 2018 (United States)",6.6,173000.0,Francis Lawrence,Justin Haythe,Jennifer Lawrence,United States,69000000.0,1.515726e+08,Chernin Entertainment,140.0
24,A Star Is Born,R,Drama,2018,"October 5, 2018 (United States)",7.6,350000.0,Bradley Cooper,Eric Roth,Lady Gaga,United States,36000000.0,4.361889e+08,Warner Bros. Pictures,136.0
25,Mamma Mia! Here We Go Again,PG-13,Comedy,2018,"July 20, 2018 (United States)",6.6,85000.0,Ol Parker,Ol Parker,Lily James,United Kingdom,75000000.0,3.956182e+08,Universal Pictures,114.0
26,Death Wish,R,Action,2018,"March 2, 2018 (United States)",6.3,67000.0,Eli Roth,Joe Carnahan,Bruce Willis,United States,30000000.0,4.956271e+07,Cave 76,107.0
27,Instant Family,PG-13,Comedy,2018,"November 16, 2018 (United States)",7.3,97000.0,Sean Anders,Sean Anders,Mark Wahlberg,United States,48000000.0,1.205562e+08,Closest to the Hole Productions,118.0
28,Jurassic World: Fallen Kingdom,PG-13,Action,2018,"June 22, 2018 (United States)",6.2,277000.0,J.A. Bayona,Derek Connolly,Chris Pratt,United States,170000000.0,1.310466e+09,Universal Pictures,128.0
29,Eighth Grade,R,Comedy,2018,"August 3, 2018 (United States)",7.4,68000.0,Bo Burnham,Bo Burnham,Elsie Fisher,United States,2000000.0,1.434743e+07,A24,93.0

In [40]:
data['genre'].value_counts()

genre
Action       88
Comedy       45
Drama        38
Biography    29
Animation    23
Adventure    19
Horror       15
Crime        12
Fantasy       3
Thriller      1
Sci-Fi        1
Name: count, dtype: int64

In [54]:
#hilangkan genre yang hanya berisi 1 judul
filter_data = data.groupby('genre').filter(lambda x: len(x) > 1)
filter_data['genre'].value_counts()

genre
Action       88
Comedy       45
Drama        38
Biography    29
Animation    23
Adventure    19
Horror       15
Crime        12
Fantasy       3
Name: count, dtype: int64

In [60]:
_, stratified_sample = train_test_split(
    filter_data,
    test_size=0.2,
    stratify=filter_data['genre'],
    random_state=53
)
sample = stratified_sample.head(30)
data_budget = sample['budget']

print("Stratified Sampling (30 data teratas):\n", sample)

Stratified Sampling (30 data teratas):
                                       name     rating      genre  year  \
74                                 Rampage      PG-13     Action  2018
256                                 Mine 9  Not Rated      Drama  2019
170                  Terminator: Dark Fate          R     Action  2019
62                               12 Strong          R     Action  2018
87                           Hotel Artemis          R     Action  2018
141        Goosebumps 2: Haunted Halloween         PG  Animation  2018
144       Once Upon a Time... In Hollywood          R     Comedy  2019
214                          What Men Want          R     Comedy  2019
182                               Hustlers          R     Comedy  2019
229                   Blinded by the Light      PG-13     Comedy  2019
57                               Bumblebee      PG-13     Action  2018
197                                  Crawl          R     Action  2019
72                               First Man      PG-13  Biography  2018
121                                  Tully          R     Comedy  2018
49                           Hunter Killer          R     Action  2018
251                              Overcomer         PG      Drama  2019
18                 Solo: A Star Wars Story      PG-13     Action  2018
129                             The Grinch         PG  Animation  2018
180         Godzilla: King of the Monsters      PG-13     Action  2019
107                Insidious: The Last Key      PG-13     Horror  2018
59   Hotel Transylvania 3: Summer Vacation         PG  Animation  2018
76                                Replicas      PG-13      Drama  2018
120                  The Happytime Murders          R     Action  2018
134    The Death & Life of John F. Donovan          R      Drama  2018
143                              Midsommar          R      Drama  2019
145                      Avengers: Endgame      PG-13     Action  2019
100                              Andhadhun  Not Rated      Crime  2018
109                                 Unsane          R      Drama  2018
167                                     Us          R     Horror  2019
228          The Art of Racing in the Rain         PG     Comedy  2019

                               released  score     votes            director  \
74       April 13, 2018 (United States)    6.1  151000.0         Brad Peyton
256               May 19, 2020 (Poland)    6.4    4400.0       Eddie Mensore
170    November 1, 2019 (United States)    6.2  159000.0          Tim Miller
62     January 19, 2018 (United States)    6.6   72000.0     Nicolai Fuglsig
87         June 8, 2018 (United States)    6.1   49000.0         Drew Pearce
141    October 12, 2018 (United States)    5.6   19000.0          Ari Sandel
144       July 26, 2019 (United States)    7.6  603000.0   Quentin Tarantino
214    February 8, 2019 (United States)    5.3   26000.0       Adam Shankman
182  September 13, 2019 (United States)    6.3   89000.0     Lorene Scafaria
229     August 16, 2019 (United States)    6.9   22000.0     Gurinder Chadha
57    December 21, 2018 (United States)    6.7  147000.0       Travis Knight
197       July 12, 2019 (United States)    6.1   74000.0       Alexandre Aja
72     October 12, 2018 (United States)    7.3  176000.0     Damien Chazelle
121         May 4, 2018 (United States)    7.0   55000.0       Jason Reitman
49     October 26, 2018 (United States)    6.6   58000.0       Donovan Marsh
251     August 23, 2019 (United States)    6.6    4100.0       Alex Kendrick
18         May 25, 2018 (United States)    6.9  306000.0          Ron Howard
129    November 9, 2018 (United States)    6.3   58000.0       Yarrow Cheney
180        May 31, 2019 (United States)    6.0  162000.0   Michael Dougherty
107     January 5, 2018 (United States)    5.7   55000.0        Adam Robitel
59        July 13, 2018 (United States)    6.3   62000.0  Genndy Tartakovsky
76     January 11, 2019 (United States)    5.5   34000.0  Jeffrey Nachmanoff
120     August 24, 2018 (United States)    5.4   26000.0        Brian Henson
134   December 13, 2019 (United States)    6.2    5900.0        Xavier Dolan
143        July 3, 2019 (United States)    7.1  232000.0           Ari Aster
145      April 26, 2019 (United States)    8.4  903000.0       Anthony Russo
100     October 5, 2018 (United States)    8.2   79000.0     Sriram Raghavan
109      March 23, 2018 (United States)    6.4   42000.0   Steven Soderbergh
167      March 22, 2019 (United States)    6.8  247000.0        Jordan Peele
228      August 9, 2019 (United States)    7.6   27000.0        Simon Curtis

                 writer                  star         country       budget  \
74           Ryan Engle        Dwayne Johnson   United States  120000000.0
256       Eddie Mensore         Terry Serpico   United States     350000.0
170      David S. Goyer        Linda Hamilton   United States  185000000.0
62            Ted Tally       Chris Hemsworth   United States   35000000.0
87          Drew Pearce          Jodie Foster  United Kingdom   15000000.0
141          Rob Lieber  Wendi McLendon-Covey   United States   35000000.0
144   Quentin Tarantino     Leonardo DiCaprio   United States   90000000.0
214         Tina Gordon      Taraji P. Henson   United States   20000000.0
182     Lorene Scafaria          Constance Wu   United States   20000000.0
229     Sarfraz Manzoor         Billy Barratt  United Kingdom   15000000.0
57     Christina Hodson      Hailee Steinfeld           China  135000000.0
197   Michael Rasmussen       Kaya Scodelario   United States   13500000.0
72          Josh Singer          Ryan Gosling   United States   59000000.0
121         Diablo Cody       Charlize Theron   United States   13000000.0
49         Arne Schmidt         Gerard Butler  United Kingdom   40000000.0
251       Alex Kendrick         Alex Kendrick   United States    5000000.0
18      Jonathan Kasdan      Alden Ehrenreich   United States  275000000.0
129     Michael LeSieur  Benedict Cumberbatch          France   75000000.0
180   Michael Dougherty         Kyle Chandler   United States  170000000.0
107      Leigh Whannell             Lin Shaye   United States   10000000.0
59   Genndy Tartakovsky          Adam Sandler   United States   80000000.0
76        Chad St. John          Keanu Reeves  United Kingdom   30000000.0
120         Todd Berger      Melissa McCarthy   United States   40000000.0
134        Xavier Dolan         Kit Harington          Canada   35000000.0
143           Ari Aster         Florence Pugh   United States    9000000.0
145  Christopher Markus     Robert Downey Jr.   United States  356000000.0
100       Arijit Biswas    Ayushmann Khurrana           India    4500000.0
109  Jonathan Bernstein            Claire Foy   United States    1500000.0
167        Jordan Peele        Lupita Nyong'o   United States   20000000.0
228        Mark Bomback         Kevin Costner   United States   18000000.0

            gross                    company  runtime
74   4.280282e+08            New Line Cinema    107.0
256  2.264210e+05             Emphatic Films     83.0
170  2.611193e+08         Paramount Pictures    128.0
62   6.745082e+07        Alcon Entertainment    130.0
87   1.331358e+07            The Ink Factory     94.0
141  9.332038e+07    Sony Pictures Animation     90.0
144  3.745658e+08          Columbia Pictures    161.0
214  7.221629e+07                  BET Films    117.0
182  1.575636e+08         Annapurna Pictures    110.0
229  1.809669e+07            New Line Cinema    118.0
57   4.679896e+08                     Hasbro    114.0
197  9.154210e+07         Paramount Pictures     87.0
72   1.057132e+08         Universal Pictures    141.0
121  1.563646e+07               BRON Studios     95.0
49   3.167613e+07  Hunter Killer Productions    121.0
251  3.802610e+07               Affirm Films    119.0
18   3.929248e+08                  Lucasfilm    135.0
129  5.124928e+08         Universal Pictures     85.0
180  3.866001e+08               Warner Bros.    132.0
107  1.678856e+08      Blumhouse Productions    103.0
59   5.285838e+08    Sony Pictures Animation     97.0
76   9.330075e+06              Company Films    107.0
120  2.750645e+07          STX Entertainment     91.0
134  3.326364e+06                 Lyla Films    123.0
143  4.796764e+07                        A24    148.0
145  2.797501e+09             Marvel Studios    181.0
100  6.247534e+07          Matchbox Pictures    139.0
109  1.429360e+07      Fingerprint Releasing     98.0
167  2.551846e+08      Monkeypaw Productions    116.0
228  3.376679e+07          Fox 2000 Pictures    109.0

In [61]:
stratified_sample.describe()

,year,score,votes,budget,gross,runtime
count,55.000000,55.000000,55.000000,5.500000e+01,5.400000e+01,55.000000
mean,2018.509091,6.609091,147489.727273,6.481555e+07,2.808547e+08,113.345455
std,0.539984,0.820630,196118.876951,7.572854e+07,4.633838e+08,19.474787
min,2018.000000,4.700000,35.000000,5.000000e+03,2.264210e+05,78.000000
25%,2018.000000,6.100000,38000.000000,1.450000e+07,3.179234e+07,99.000000
50%,2018.000000,6.600000,74000.000000,3.100000e+07,1.008160e+08,112.000000
75%,2019.000000,7.200000,172000.000000,8.500000e+07,3.723122e+08,122.000000
max,2020.000000,8.400000,1000000.000000,3.560000e+08,2.797501e+09,181.000000

In [72]:
import scipy.stats as stats
import math

x_bar = 6.48 #rata-rata
s = 7.57 # std sample (standar deviasi)
n = 30 # jumlah data(sampel)
confidence_level = 0.90 # pilih antara 0.90 / 0.95 / 0.99

alpha = (1 - confidence_level) # mencari alpha
df = n - 1
standard_error = s/math.sqrt(n)
critical_t = stats.t.ppf(1 - alpha/2, df)
margin_of_error = critical_t * standard_error

lower_bound = x_bar - margin_of_error
upper_bound = x_bar + margin_of_error

print("Critical t-value: {:.2f}".format(critical_t))
print("Margin of Error: {:.2f}".format(margin_of_error))
print("Confidence Interval: [{:.2f},{:.2f}]".format(lower_bound, upper_bound))
print("The {:.1%} confidence interval for the population mean is:".format(confidence_level))
print("between {:.2f} and {:.2f}".format(lower_bound, upper_bound))

Critical t-value: 1.70
Margin of Error: 2.35
Confidence Interval: [4.13,8.83]
The 90.0% confidence interval for the population mean is:
between 4.13 and 8.83